# Import

In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
from sklearn.metrics.pairwise import cosine_similarity

# Loading

In [6]:
data = pd.read_csv('User_Product_df.csv', index_col='CustomerID')

In [7]:
data.head()

00DM28LT  013E5SFQ  01APE0T4  01G6QD1T  01NB3B3M  01TR4FQF  \
CustomerID                                                               
12339              0         0         0         0         0         0   
12340              0         0         0         0         0         0   
12346              0         0         0         0         0         0   
12347              0         0         0         0         0         0   
12348              0         0         0         0         0         0   

            01XJF3DT  023FOB8V  03VBIVAR  04DEZ789  ...  ZY9C2UXD  ZYGY58IP  \
CustomerID                                          ...                       
12339              0         0         0         0  ...         0         0   
12340              0         0         0         0  ...         0         0   
12346              0         0         0         0  ...         0         0   
12347              0         0         0         0  ...         0         0   
12348              0         0         0         0  ...         0         0   

            ZYHE5SNM  ZYJJBM9A  ZYXG1HRO  ZZ28J9SM  ZZ5FG3VP  ZZANPY4R  \
CustomerID                                                               
12339              0         0         0         0         0         0   
12340              0         0         0         0         0         0   
12346              0         0         0         0         0         0   
12347              0         0         0         0         0         0   
12348              0         0         0         0         0         0   

            ZZF9OLGI  ZZWWYVS6  
CustomerID                      
12339              0         0  
12340              0         0  
12346              0         0  
12347              0         0  
12348              0         0  

[5 rows x 4223 columns]

In [8]:
df = data.copy()

In [9]:
fullData = pd.read_csv('Product_Dataset.csv')

In [10]:
fdf = fullData.copy()

# Codes : Collaborative Filtering

In [11]:
similarities = cosine_similarity(df)

In [12]:
df

00DM28LT  013E5SFQ  01APE0T4  01G6QD1T  01NB3B3M  01TR4FQF  \
CustomerID                                                               
12339              0         0         0         0         0         0   
12340              0         0         0         0         0         0   
12346              0         0         0         0         0         0   
12347              0         0         0         0         0         0   
12348              0         0         0         0         0         0   
...              ...       ...       ...       ...       ...       ...   
99766              0         0         0         0         0         0   
99791              0         0         0         0         0         0   
99859              0         0         0         0         0         0   
99882              0         0         1         0         0         0   
99886              0         0         0         0         0         0   

            01XJF3DT  023FOB8V  03VBIVAR  04DEZ789  ...  ZY9C2UXD  ZYGY58IP  \
CustomerID                                          ...                       
12339              0         0         0         0  ...         0         0   
12340              0         0         0         0  ...         0         0   
12346              0         0         0         0  ...         0         0   
12347              0         0         0         0  ...         0         0   
12348              0         0         0         0  ...         0         0   
...              ...       ...       ...       ...  ...       ...       ...   
99766              0         0         0         0  ...         0         0   
99791              0         0         0         0  ...         0         0   
99859              0         0         0         0  ...         0         0   
99882              1         0         0         0  ...         0         0   
99886              0         0         0         0  ...         0         0   

            ZYHE5SNM  ZYJJBM9A  ZYXG1HRO  ZZ28J9SM  ZZ5FG3VP  ZZANPY4R  \
CustomerID                                                               
12339              0         0         0         0         0         0   
12340              0         0         0         0         0         0   
12346              0         0         0         0         0         0   
12347              0         0         0         0         0         0   
12348              0         0         0         0         0         0   
...              ...       ...       ...       ...       ...       ...   
99766              0         0         0         0         0         0   
99791              0         0         0         0         0         0   
99859              0         0         0         0         0         0   
99882              0         0         0         0         0         0   
99886              0         0         0         0         0         0   

            ZZF9OLGI  ZZWWYVS6  
CustomerID                      
12339              0         0  
12340              0         0  
12346              0         0  
12347              0         0  
12348              0         0  
...              ...       ...  
99766              0         0  
99791              0         0  
99859              0         0  
99882              0         0  
99886              0         0  

[6627 rows x 4223 columns]

In [13]:
similarities

array([[1.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 1.        , 0.        , ..., 0.16035675, 0.01403034,
        0.        ],
       [0.        , 0.        , 1.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.16035675, 0.        , ..., 1.        , 0.10499344,
        0.        ],
       [0.        , 0.01403034, 0.        , ..., 0.10499344, 1.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        1.        ]])

In [14]:
ndf = pd.DataFrame(data=similarities, index=df.index.values, columns= df.index.values)

In [15]:
xx = ndf[14000].sort_values(ascending = False).head(3)
xx

14000    1.00000
17414    0.46188
16377    0.46188
Name: 14000, dtype: float64

In [16]:
xx.values

array([1.        , 0.46188022, 0.46188022])

In [17]:
# Function to get bought productCode by given customerID

def boughtProductCode(cID:int)->list:
    bought = []
    tmp = list(df.loc[cID].items())
    for x in tmp:
        if x[1] == 1:
            bought.append(x[0])
    
    return bought

In [18]:
tmp = list(df.loc[12340].items())

In [19]:
tmp[0:5]

[('00DM28LT', 0),
 ('013E5SFQ', 0),
 ('01APE0T4', 0),
 ('01G6QD1T', 0),
 ('01NB3B3M', 0)]

In [20]:
op =['98','98','8']
op = set(op)
op

{'8', '98'}

In [21]:
def getProductName(prodCode:str):
    return fdf[fdf['ProdCode'] == prodCode]['Description'].values[0]

In [56]:
def getRecommendations(userId:int):
    xx = ndf[userId].sort_values(ascending = False).head(5)
    similar_users = xx.index[1:].values
    sim_user_ratings = xx.values[1:]

    prodCodes = []
    for user in similar_users:
        for x in boughtProductCode(user):
            prodCodes.append(x)

    prodCodes = set(prodCodes) - set(boughtProductCode(userId)) # refined already purchased product from recommended products
    
    prodNames = []
    for code in prodCodes:
        prodNames.append(getProductName(code))


    return prodNames, [similar_users, sim_user_ratings]


In [57]:
x,y = getRecommendations(14000)
x

['FAN BLACK FRAME ', 'MEDIUM CHINESE STYLE SCISSOR']

In [58]:
y

[array([17414, 16377, 13848, 12864], dtype=int64),
 array([0.46188022, 0.46188022, 0.2981424 , 0.2981424 ])]

## Non-Importan. No need to implement

In [47]:
for x in boughtProductCode(14000):
    print(getProductName(x))

FIRE POLISHED GLASS BRACELET MONTAN
PINK PAPER PARASOL 
ASSORTED COLOUR T-LIGHT HOLDER
MULTI COLOUR SILVER T-LIGHT HOLDER
RED PAPER PARASOL
MOROCCAN TEA GLASS
SMALL CHINESE STYLE SCISSOR
FIRE POLISHED GLASS BRACELET GREEN
BLUE PAISLEY SKETCHBOOK
BROCADE RING PURSE 
FIRE POLISHED GLASS BRACELET RED
SANDALWOOD FAN
BLUE PAPER PARASOL 
ASSORTED COLOURS SILK FAN
LARGE CHINESE STYLE SCISSOR


In [59]:
for x in boughtProductCode(12864):
    print(getProductName(x))

FAN BLACK FRAME 
SANDALWOOD FAN
ASSORTED COLOURS SILK FAN
